### ISSUE TITLE
Unable to add Filters when using the Import button

### ISSUE THREAD

**Issue by Ankit1598** [benwinding/react-admin-import-csv#59]
The Import button on its own works fine but the Filter is not visible, so then I followed Issue #1 but then I started getting error.

In my code I have:
```js
const QuestionListActions = (props) => {
	const { className, basePath, total, resource, currentSort, filterValues, exporter } = props;
	const config = {
		logging: true,
		validateRow: async (row) => {
			if (row.id) {
				// throw new Error("AAAA");
			}
		},
		postCommitCallback: (reportItems) => {
			console.log("reportItems", { reportItems });
		},
		// disableImportNew: true,
		// disableImportOverwrite: true,
	};
	return (
		<TopToolbar className={className}>
			<QuestionFilter {...props}/>
			<CreateButton basePath={basePath} />
			<ExportButton
				disabled={total === 0}
				resource={resource}
				sort={currentSort}
				filter={filterValues}
				exporter={exporter}
			/>
			<ImportButton
				{...props}
				{...config}
				parseConfig={{ dynamicTyping: true }}
			/>
		</TopToolbar>
	);
};

const QuestionFilter = (props) => (
	<Filter {...props}>
		<TextInput label='Search' source='q' alwaysOn />
		<ReferenceInput
			label='User'
			source='userId'
			reference='users'
			allowEmpty
		>
			<SelectInput optionText='name' />
		</ReferenceInput>
	</Filter>
);

export const QuestionList = (props) => (
	<List {...props} actions={<QuestionListActions />}>
		<Datagrid>
			<TextField source='id' />
			<ReferenceField label='User' source='userId' reference='users'>
				<TextField source='name' />
			</ReferenceField>
			<TextField source='question' />
			<TextField source='answer' />
			<EditButton base='/questions' />
			<ShowButton base='/questions' />
			<DeleteButton base='/questions' />
		</Datagrid>
	</List>
);
```
Below is the error log that I am getting
![image](https://user-images.githubusercontent.com/65450600/113503410-8b932f80-94e6-11eb-8968-e898b2189ae6.png)

```
TypeError: Cannot read property 'filter' of undefined

    at EnhancedFilterForm (http://localhost:3000/static/js/vendors~main.chunk.js:268632:31)
    at Filter (http://localhost:3000/static/js/vendors~main.chunk.js:268189:17)
    at div
    at Toolbar (http://localhost:3000/static/js/vendors~main.chunk.js:31883:23)
    at WithStyles(ForwardRef(Toolbar)) (http://localhost:3000/static/js/vendors~main.chunk.js:180170:31)
    at TopToolbar (http://localhost:3000/static/js/vendors~main.chunk.js:264811:25)
    at ListActions (http://localhost:3000/static/js/main.chunk.js:451:5)
    at div
    at Toolbar (http://localhost:3000/static/js/vendors~main.chunk.js:31883:23)
    at WithStyles(ForwardRef(Toolbar)) (http://localhost:3000/static/js/vendors~main.chunk.js:180170:31)
    at ListToolbar (http://localhost:3000/static/js/vendors~main.chunk.js:265783:31)
    at div
    at ListView (http://localhost:3000/static/js/vendors~main.chunk.js:265877:23)
    at ListContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:221843:18)
    at List (http://localhost:3000/static/js/vendors~main.chunk.js:265460:79)
    at QuestionList
   ```

**Comment by techpet** [comment]
This is how I managed to solve this by following the tutorial on:
[https://marmelab.com/react-admin/List.html#actions](https://marmelab.com/react-admin/List.html#actions)

as @benwinding suggested in [#1](https://github.com/benwinding/react-admin-import-csv/issues/1)

```
// ...other imports
import { cloneElement } from "react";

const Filters = (props) => (
    <Filter {...props}>
    <TextInput label="Title" source="title" default="Hello World"/>
    </Filter>
);

const ListActions = (props) => {
  const {
    className,
    basePath,
    total,
    resource,
    currentSort,
    filterValues,
    exporter,
  } = props;
  return (
    <TopToolbar className={className}  >
      {cloneElement(props.filters, { context: 'button' })}
      <CreateButton basePath={basePath} />
      <ImportButton {...props} {...config} />
      <ExportButton
        disabled={total === 0}
        resource={resource}
        sort={currentSort}
        filter={filterValues}
        exporter={exporter}
      />
    </TopToolbar>
  );
};

const ExampleList = ({ permissions, ...props }) => (
    <List
      {...props}
      actions={<ListActions {...props}/>}
      filters={<Filters  {...props}/>}
    >
   ...
```
